[2025-03-12T15:15:20.962+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline scheduled__2025-03-12T15:10:00+00:00 [queued]>
[2025-03-12T15:15:20.971+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline scheduled__2025-03-12T15:10:00+00:00 [queued]>
[2025-03-12T15:15:20.971+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T15:15:21.091+0000] {taskinstance.py:1382} INFO - Executing <Task(TriggerDagRunOperator): trigger_hourly_pipeline> on 2025-03-12 15:10:00+00:00
[2025-03-12T15:15:21.093+0000] {standard_task_runner.py:57} INFO - Started process 38786 to run task
[2025-03-12T15:15:21.096+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_bronze_and_silver_layer', 'trigger_hourly_pipeline', 'scheduled__2025-03-12T15:10:00+00:00', '--job-id', '2920', '--raw', '--subdir', 'DAGS_FOLDER/5mins_processing_pipeline.py', '--cfg-path', '/tmp/tmpxkv_rmli']
[2025-03-12T15:15:21.098+0000] {standard_task_runner.py:85} INFO - Job 2920: Subtask trigger_hourly_pipeline
[2025-03-12T15:15:21.129+0000] {task_command.py:416} INFO - Running <TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline scheduled__2025-03-12T15:10:00+00:00 [running]> on host c8e526380ef3
[2025-03-12T15:15:21.214+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='process_bronze_and_silver_layer' AIRFLOW_CTX_TASK_ID='trigger_hourly_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T15:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T15:10:00+00:00'
[2025-03-12T15:15:21.230+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/trigger_dagrun.py", line 163, in execute
    dag_run = trigger_dag(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/api/common/trigger_dag.py", line 122, in trigger_dag
    triggers = _trigger_dag(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/api/common/trigger_dag.py", line 52, in _trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found")
airflow.exceptions.DagNotFound: Dag id hourly_processing_pipeline not found
[2025-03-12T15:15:21.234+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_bronze_and_silver_layer, task_id=trigger_hourly_pipeline, execution_date=20250312T151000, start_date=20250312T151520, end_date=20250312T151521
[2025-03-12T15:15:21.244+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2920 for task trigger_hourly_pipeline (Dag id hourly_processing_pipeline not found; 38786)
[2025-03-12T15:15:21.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T15:15:21.299+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
