[2025-03-11T04:56:38.629+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.task_date manual__2025-03-11T04:55:58+00:00 [queued]>
[2025-03-11T04:56:38.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.task_date manual__2025-03-11T04:55:58+00:00 [queued]>
[2025-03-11T04:56:38.633+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2025-03-11T04:56:38.638+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_date> on 2025-03-11 04:55:58+00:00
[2025-03-11T04:56:38.640+0000] {standard_task_runner.py:57} INFO - Started process 5319 to run task
[2025-03-11T04:56:38.642+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_layer_dag', 'task_date', 'manual__2025-03-11T04:55:58+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/ingesting_pipeline.py', '--cfg-path', '/tmp/tmpwqlyvdkt']
[2025-03-11T04:56:38.643+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask task_date
[2025-03-11T04:56:38.663+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_bronze_layer_dag.task_date manual__2025-03-11T04:55:58+00:00 [running]> on host 50aa08a06197
[2025-03-11T04:56:38.818+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'task_date', field 'bash_command'. Template: 'echo \'{{ ti.get_previous_start_date(state="success").strftime("%Y-%m-%d %H:%M:%S") if (ti.get_previous_start_date(state="success") and params.full == "False") else "1900-01-01 00:00:00" }}\''
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'full'
[2025-03-11T04:56:38.819+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 112, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'full'
[2025-03-11T04:56:38.822+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_bronze_layer_dag, task_id=task_date, execution_date=20250311T045558, start_date=20250311T045638, end_date=20250311T045638
[2025-03-11T04:56:38.827+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task task_date ('dict object' has no attribute 'full'; 5319)
[2025-03-11T04:56:38.874+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T04:56:38.887+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
