[2025-03-11T15:05:03.981+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.extract_and_load_purchases scheduled__2025-03-11T15:00:00+00:00 [queued]>
[2025-03-11T15:05:03.985+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.extract_and_load_purchases scheduled__2025-03-11T15:00:00+00:00 [queued]>
[2025-03-11T15:05:03.985+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T15:05:03.991+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_load_purchases> on 2025-03-11 15:00:00+00:00
[2025-03-11T15:05:03.993+0000] {standard_task_runner.py:57} INFO - Started process 17802 to run task
[2025-03-11T15:05:03.995+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_layer_dag', 'extract_and_load_purchases', 'scheduled__2025-03-11T15:00:00+00:00', '--job-id', '485', '--raw', '--subdir', 'DAGS_FOLDER/ingesting_pipeline.py', '--cfg-path', '/tmp/tmpr4gg7j35']
[2025-03-11T15:05:03.996+0000] {standard_task_runner.py:85} INFO - Job 485: Subtask extract_and_load_purchases
[2025-03-11T15:05:04.091+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_bronze_layer_dag.extract_and_load_purchases scheduled__2025-03-11T15:00:00+00:00 [running]> on host 41ccd9d1769c
[2025-03-11T15:05:09.155+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='ingest_bronze_layer_dag' AIRFLOW_CTX_TASK_ID='extract_and_load_purchases' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T15:00:00+00:00'
[2025-03-11T15:05:09.177+0000] {base.py:73} INFO - Using connection ID 'postgres_source_db' for task execution.
[2025-03-11T15:05:09.182+0000] {warnings.py:109} WARNING - /opt/***/dags/ingesting_pipeline.py:136: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

[2025-03-11T15:05:09.184+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2262, in execute
    cur.execute(sql, *args)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: "None"
LINE 4:             WHERE updated_at > 'None'
                                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingesting_pipeline.py", line 360, in extract_and_load_purchases
    df = extract_data_from_source(pg_source_hook, query)
  File "/opt/airflow/dags/ingesting_pipeline.py", line 136, in extract_data_from_source
    df = pd.read_sql(query, conn)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 654, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2326, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2274, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
            SELECT *, NOW() as extracted_at
            FROM app_source.purchases_data
            WHERE updated_at > 'None'
        ': invalid input syntax for type timestamp: "None"
LINE 4:             WHERE updated_at > 'None'
                                       ^

[2025-03-11T15:05:09.189+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ingest_bronze_layer_dag, task_id=extract_and_load_purchases, execution_date=20250311T150000, start_date=20250311T150503, end_date=20250311T150509
[2025-03-11T15:05:09.196+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 485 for task extract_and_load_purchases (Execution failed on sql '
            SELECT *, NOW() as extracted_at
            FROM app_source.purchases_data
            WHERE updated_at > 'None'
        ': invalid input syntax for type timestamp: "None"
LINE 4:             WHERE updated_at > 'None'
                                       ^
; 17802)
[2025-03-11T15:05:09.214+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T15:05:09.224+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
