[2025-03-12T07:05:20.723+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:04:53+00:00 [queued]>
[2025-03-12T07:05:20.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:04:53+00:00 [queued]>
[2025-03-12T07:05:20.728+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T07:05:20.845+0000] {taskinstance.py:1382} INFO - Executing <Task(TriggerDagRunOperator): trigger_hourly_pipeline> on 2025-03-12 07:04:53+00:00
[2025-03-12T07:05:20.848+0000] {standard_task_runner.py:57} INFO - Started process 18805 to run task
[2025-03-12T07:05:20.850+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_bronze_and_silver_layer', 'trigger_hourly_pipeline', 'manual__2025-03-12T07:04:53+00:00', '--job-id', '1516', '--raw', '--subdir', 'DAGS_FOLDER/5mins_processing_pipeline.py', '--cfg-path', '/tmp/tmp52j7t6rj']
[2025-03-12T07:05:20.852+0000] {standard_task_runner.py:85} INFO - Job 1516: Subtask trigger_hourly_pipeline
[2025-03-12T07:05:20.874+0000] {task_command.py:416} INFO - Running <TaskInstance: process_bronze_and_silver_layer.trigger_hourly_pipeline manual__2025-03-12T07:04:53+00:00 [running]> on host c8e526380ef3
[2025-03-12T07:05:20.910+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='process_bronze_and_silver_layer' AIRFLOW_CTX_TASK_ID='trigger_hourly_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T07:04:53+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T07:04:53+00:00'
[2025-03-12T07:05:20.913+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/trigger_dagrun.py", line 153, in execute
    json.dumps(self.conf)
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/trigger_dagrun.py", line 155, in execute
    raise AirflowException("conf parameter should be JSON Serializable")
airflow.exceptions.AirflowException: conf parameter should be JSON Serializable
[2025-03-12T07:05:20.915+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_bronze_and_silver_layer, task_id=trigger_hourly_pipeline, execution_date=20250312T070453, start_date=20250312T070520, end_date=20250312T070520
[2025-03-12T07:05:20.921+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1516 for task trigger_hourly_pipeline (conf parameter should be JSON Serializable; 18805)
[2025-03-12T07:05:20.959+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T07:05:20.970+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
