[2025-03-11T04:41:56.531+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.fetch_purchases scheduled__2025-03-11T04:35:00+00:00 [queued]>
[2025-03-11T04:41:56.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.fetch_purchases scheduled__2025-03-11T04:35:00+00:00 [queued]>
[2025-03-11T04:41:56.536+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T04:41:56.544+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): fetch_purchases> on 2025-03-11 04:35:00+00:00
[2025-03-11T04:41:56.549+0000] {standard_task_runner.py:57} INFO - Started process 4719 to run task
[2025-03-11T04:41:56.551+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_layer_dag', 'fetch_purchases', 'scheduled__2025-03-11T04:35:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/ingesting_pipeline.py', '--cfg-path', '/tmp/tmpnd0ngspu']
[2025-03-11T04:41:56.554+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask fetch_purchases
[2025-03-11T04:41:56.584+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_bronze_layer_dag.fetch_purchases scheduled__2025-03-11T04:35:00+00:00 [running]> on host 50aa08a06197
[2025-03-11T04:41:56.623+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='ingest_bronze_layer_dag' AIRFLOW_CTX_TASK_ID='fetch_purchases' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T04:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T04:35:00+00:00'
[2025-03-11T04:41:56.631+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingesting_pipeline.py", line 48, in fetch_purchases
    conn = pg_source_hook.get_conn()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 125, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_source_db` isn't defined
[2025-03-11T04:41:56.633+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ingest_bronze_layer_dag, task_id=fetch_purchases, execution_date=20250311T043500, start_date=20250311T044156, end_date=20250311T044156
[2025-03-11T04:41:56.640+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task fetch_purchases (The conn_id `postgres_source_db` isn't defined; 4719)
[2025-03-11T04:41:56.645+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T04:41:56.652+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
