[2025-03-12T08:44:24.027+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_processing_pipeline.check_refresh_mode manual__2025-03-12T08:44:22.126892+00:00 [queued]>
[2025-03-12T08:44:24.035+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_processing_pipeline.check_refresh_mode manual__2025-03-12T08:44:22.126892+00:00 [queued]>
[2025-03-12T08:44:24.036+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T08:44:24.083+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): check_refresh_mode> on 2025-03-12 08:44:22.126892+00:00
[2025-03-12T08:44:24.088+0000] {standard_task_runner.py:57} INFO - Started process 24560 to run task
[2025-03-12T08:44:24.093+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hourly_processing_pipeline', 'check_refresh_mode', 'manual__2025-03-12T08:44:22.126892+00:00', '--job-id', '2050', '--raw', '--subdir', 'DAGS_FOLDER/hourly_processing_pipeline.py', '--cfg-path', '/tmp/tmpqbtcipaw']
[2025-03-12T08:44:24.096+0000] {standard_task_runner.py:85} INFO - Job 2050: Subtask check_refresh_mode
[2025-03-12T08:44:24.475+0000] {task_command.py:416} INFO - Running <TaskInstance: hourly_processing_pipeline.check_refresh_mode manual__2025-03-12T08:44:22.126892+00:00 [running]> on host c8e526380ef3
[2025-03-12T08:44:24.528+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='hourly_processing_pipeline' AIRFLOW_CTX_TASK_ID='check_refresh_mode' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T08:44:22.126892+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T08:44:22.126892+00:00'
[2025-03-12T08:44:24.529+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hourly_processing_pipeline.py", line 213, in check_refresh_mode
    logger.info(f"Refresh mode: {'Full Refresh' if is_full_refresh else 'Incremental'}")
UnboundLocalError: local variable 'is_full_refresh' referenced before assignment
[2025-03-12T08:44:24.540+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hourly_processing_pipeline, task_id=check_refresh_mode, execution_date=20250312T084422, start_date=20250312T084424, end_date=20250312T084424
[2025-03-12T08:44:24.550+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2050 for task check_refresh_mode (local variable 'is_full_refresh' referenced before assignment; 24560)
[2025-03-12T08:44:24.568+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T08:44:25.145+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
